owner: koj-co
repo: status.kojdev.com
sites:
  - name: Dev website
    url: https://kojdev.com
  - name: Dev API
    url: https://api.kojdev.com
  - name: Dev admin panel
    url: https://admin.kojdev.com
status-website:
  cname: status.kojdev.com
  name: Koj Staging Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
